[project]
site_name = "pydgens"
site_description = "Python/JAX numerical solvers for dynamic and differential game equilibria."
site_author = "R. Allen, W. Li"
site_url = "https://mit-ll.github.io/pydgens/"
copyright = """
Copyright &copy; 2026 Massachusetts Institute of Technology
"""
nav = [
  { "Get started" = "index.md" },
  { "Examples" = "examples.md" },
  { "Solvers" = "solvers.md" },
  { "API Reference" = "api.md" },
  { "Testing" = "testing.md" },
  { "Profiling" = "profile.md" },
  { "References" = "references.md" },
  { "License" = "license.md" },
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
filters = "public"
members_order = "__all__"
show_root_heading = true
show_root_full_path = false
show_source = false

[project.theme]
language = "en"
features = [
  "content.code.annotate",
  "content.code.copy",
  "content.tabs.link",
  "navigation.footer",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
